<a href="https://colab.research.google.com/github/Calm-leon/proyecto-an-lisis-de-datos/blob/correcci%C3%B3n/Puchamon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Foundations of Data Science Project - Diabetes Analysis

---------------
## Context
---------------

en el universo pokemon encontramos diferentes pokemones 

-----------------
## Objective
-----------------

Here, we are analyzing different aspects of Diabetes in the Pima Diabetes Analysis by doing Exploratory Data Analysis.

-------------------------
## Data Dictionary
-------------------------

The dataset has the following information:

* Pregnancies: Number of times pregnant
* Glucose: Plasma glucose concentration over 2 hours in an oral glucose tolerance test
* BloodPressure: Diastolic blood pressure (mm Hg)
* SkinThickness: Triceps skin fold thickness (mm)
* Insulin: 2-Hour serum insulin (mu U/ml)
* BMI: Body mass index (weight in kg/(height in m)^2)
* DiabetesPedigreeFunction: A function that scores the likelihood of diabetes based on family history.
* Age: Age in years
* Outcome: Class variable (0: a person is not diabetic or 1: a person is diabetic)

## Q 1: Importación de bibliotecas a usar.

In [103]:
import numpy as np # NumPy crea arreglos de grandes dimensiones y contiene un gran número de funciones matemátematicas de alto nivel para tranajar con ellos. 
import pandas as pd # Pandas nos facilita la manipulación, tratamiento y análisis de los datos.
import seaborn as sns # Seabron (desarrollada sobre matplotlib) nos ofrese la visualización de los datos; con creación de trazado estadiaticos.
import matplotlib.pyplot as plt # Matplotlib libreria espacialisada en trazado para graficos en dos dimenciones.
import scipy.stats as stats # Scipy contiene una gran cantidad de distribuciones estadisticas y mas especifico .stats se utiliza para analizar la distribución normal.
%matplotlib inline

#### Write your Answer here:

In [104]:
Pokemon = pd.read_csv("https://raw.githubusercontent.com/MuhammadBilalTahir/What-makes-a-Pokemon-Legendary/main/pokedex.csv")

In [105]:
#quitamos lo que no usaremos
Pokemon=Pokemon.drop(['percentage_male','type','generation'],axis=1)
Pokemon

,pokedex_number,name,attack,defense,height_m,hp,sp_attack,sp_defense,speed,weight_kg,is_legendary
0,1,Bulbasaur,49,49,0.7,45,65,65,45,6.9,0
1,2,Ivysaur,62,63,1.0,60,80,80,60,13.0,0
2,3,Venusaur,100,123,2.0,80,122,120,80,100.0,0
3,4,Charmander,52,43,0.6,39,60,50,65,8.5,0
4,5,Charmeleon,64,58,1.1,58,80,65,80,19.0,0
...,...,...,...,...,...,...,...,...,...,...,...
796,797,Celesteela,101,103,9.2,97,107,101,61,999.9,1
797,798,Kartana,181,131,0.3,59,59,31,109,0.1,1
798,799,Guzzlord,101,53,5.5,223,97,53,43,888.0,1
799,800,Necrozma,107,101,2.4,97,127,89,79,230.0,1
800,801,Magearna,95,115,1.0,80,130,115,65,80.5,1

In [106]:
FiltroHeight = Pokemon.height_m.isnull()
Vacioheight_m=Pokemon.height_m[FiltroHeight]
#Vacioheight_m.shape
Vacioheight_m
Pokemon.height_m[18]=1.5
Pokemon.height_m[19]=0.3
Pokemon.height_m[25]=0.4
Pokemon.height_m[26]=0.8
Pokemon.height_m[27]=0.6
Pokemon.height_m[36]=1.3
Pokemon.height_m[37]=0.6
Pokemon.height_m[49]=1.5
Pokemon.height_m[50]=0.2
Pokemon.height_m[51]=0.7
Pokemon.height_m[52]=0.4
Pokemon.height_m[73]=1.6
Pokemon.height_m[74]=0.4
Pokemon.height_m[75]=1
Pokemon.height_m[87]=1.7
Pokemon.height_m[88]=0.9
Pokemon.height_m[102]=0.4
Pokemon.height_m[104]=0.4
Pokemon.height_m[719]=0.7
Pokemon.height_m[744]=0.5

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [107]:
FiltroWeight = Pokemon.weight_kg.isnull()
Vacioweight_kg=Pokemon.weight_kg[FiltroWeight]
Pokemon.weight_kg[18]=39.5
Pokemon.weight_kg[19]=3.5
Pokemon.weight_kg[25]=6
Pokemon.weight_kg[26]=30
Pokemon.weight_kg[27]=12
Pokemon.weight_kg[36]=40
Pokemon.weight_kg[37]=9.9
Pokemon.weight_kg[49]=12.5
Pokemon.weight_kg[50]=0.8
Pokemon.weight_kg[51]=33.3
Pokemon.weight_kg[52]=4.2
Pokemon.weight_kg[73]=55
Pokemon.weight_kg[74]=20
Pokemon.weight_kg[75]=105
Pokemon.weight_kg[87]=120
Pokemon.weight_kg[88]=30
Pokemon.weight_kg[102]=2.5
Pokemon.weight_kg[104]=6.5
Pokemon.weight_kg[719]=8.8
Pokemon.weight_kg[744]=9.2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [108]:
Pokemon.describe()
Pokemon.info()
Pokemon

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pokedex_number  801 non-null    int64
 1   name            801 non-null    object
 2   attack          801 non-null    int64
 3   defense         801 non-null    int64
 4   height_m        801 non-null    float64
 5   hp              801 non-null    int64
 6   sp_attack       801 non-null    int64
 7   sp_defense      801 non-null    int64
 8   speed           801 non-null    int64
 9   weight_kg       801 non-null    float64
 10  is_legendary    801 non-null    int64
dtypes: float64(2), int64(8), object(1)
memory usage: 69.0+ KB

,pokedex_number,name,attack,defense,height_m,hp,sp_attack,sp_defense,speed,weight_kg,is_legendary
0,1,Bulbasaur,49,49,0.7,45,65,65,45,6.9,0
1,2,Ivysaur,62,63,1.0,60,80,80,60,13.0,0
2,3,Venusaur,100,123,2.0,80,122,120,80,100.0,0
3,4,Charmander,52,43,0.6,39,60,50,65,8.5,0
4,5,Charmeleon,64,58,1.1,58,80,65,80,19.0,0
...,...,...,...,...,...,...,...,...,...,...,...
796,797,Celesteela,101,103,9.2,97,107,101,61,999.9,1
797,798,Kartana,181,131,0.3,59,59,31,109,0.1,1
798,799,Guzzlord,101,53,5.5,223,97,53,43,888.0,1
799,800,Necrozma,107,101,2.4,97,127,89,79,230.0,1
800,801,Magearna,95,115,1.0,80,130,115,65,80.5,1

In [109]:
# Entrem mas gordo y mas grande mas lento puede ser, para compenzarlo subiremos su velocidad base a su altura y peso
Pokemon2=Pokemon.drop(['is_legendary'],axis=1)
Friccion = (Pokemon.height_m + Pokemon.weight_kg)/10
Friccion = pd.DataFrame(Friccion, columns = ['Friccion'])
Pokemon2=pd.concat([Pokemon2,Friccion], axis=1)
Pokemon=pd.concat([Pokemon2,Pokemon.is_legendary], axis=1)

In [110]:
#Velocidades resultantes luego de la equilibracion 
sp_attackdef = (Pokemon.sp_attack + Pokemon.Friccion)
sp_defensedef = (Pokemon.sp_defense +  Pokemon.Friccion)
speeddef = (Pokemon.speed +  Pokemon.Friccion)
sp_attackdef = pd.DataFrame(sp_attackdef, columns = ['sp_attackdef'])
sp_defensedef = pd.DataFrame(sp_defensedef, columns = ['sp_defensedef'])
speeddef = pd.DataFrame(speeddef, columns = ['speeddef'])
Pokemon2=Pokemon.drop(['is_legendary'],axis=1)
Pokemon2=pd.concat([Pokemon2,sp_attackdef,sp_defensedef,speeddef], axis=1)
Pokemon=pd.concat([Pokemon2,Pokemon.is_legendary], axis=1)
#Pokemon = Pokemon.drop(['height_m','sp_attack','sp_defense','speed','weight_kg'],axis=1)
Pokemon

,pokedex_number,name,attack,defense,height_m,hp,sp_attack,sp_defense,speed,weight_kg,Friccion,sp_attackdef,sp_defensedef,speeddef,is_legendary
0,1,Bulbasaur,49,49,0.7,45,65,65,45,6.9,0.76,65.76,65.76,45.76,0
1,2,Ivysaur,62,63,1.0,60,80,80,60,13.0,1.40,81.40,81.40,61.40,0
2,3,Venusaur,100,123,2.0,80,122,120,80,100.0,10.20,132.20,130.20,90.20,0
3,4,Charmander,52,43,0.6,39,60,50,65,8.5,0.91,60.91,50.91,65.91,0
4,5,Charmeleon,64,58,1.1,58,80,65,80,19.0,2.01,82.01,67.01,82.01,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,797,Celesteela,101,103,9.2,97,107,101,61,999.9,100.91,207.91,201.91,161.91,1
797,798,Kartana,181,131,0.3,59,59,31,109,0.1,0.04,59.04,31.04,109.04,1
798,799,Guzzlord,101,53,5.5,223,97,53,43,888.0,89.35,186.35,142.35,132.35,1
799,800,Necrozma,107,101,2.4,97,127,89,79,230.0,23.24,150.24,112.24,102.24,1
800,801,Magearna,95,115,1.0,80,130,115,65,80.5,8.15,138.15,123.15,73.15,1

In [101]:
# El ataque, defensa y vida es lo mas importante seguido de la velocidad, asi mismo la velocidad de ataque y defensa tabien tienen peso 
PoderPuchamon = (Pokemon.attack*5 + Pokemon.defense*5 + Pokemon.hp*5 + Pokemon.sp_attackdef*3 + Pokemon.sp_defensedef*3 + Pokemon.speeddef*4 )/20
PoderPuchamon = pd.DataFrame(PoderPuchamon, columns = ['PoderPuchamon'])
Pokemon2=Pokemon.drop(['is_legendary'],axis=1)
Pokemon2=pd.concat([Pokemon2,PoderPuchamon], axis=1)
Pokemon=pd.concat([Pokemon2,Pokemon.is_legendary], axis=1)
Pokemon

,pokedex_number,name,attack,defense,hp,Friccion,sp_attackdef,sp_defensedef,speeddef,PoderPuchamon,is_legendary
0,1,Bulbasaur,49,49,45,0.76,65.76,65.76,45.76,64.630,0
1,2,Ivysaur,62,63,60,1.40,81.40,81.40,61.40,82.950,0
2,3,Venusaur,100,123,80,10.20,132.20,130.20,90.20,133.150,0
3,4,Charmander,52,43,39,0.91,60.91,50.91,65.91,63.455,0
4,5,Charmeleon,64,58,58,2.01,82.01,67.01,82.01,83.755,0
...,...,...,...,...,...,...,...,...,...,...,...
796,797,Celesteela,101,103,97,100.91,207.91,201.91,161.91,169.105,1
797,798,Kartana,181,131,59,0.04,59.04,31.04,109.04,128.070,1
798,799,Guzzlord,101,53,223,89.35,186.35,142.35,132.35,170.025,1
799,800,Necrozma,107,101,97,23.24,150.24,112.24,102.24,136.070,1
800,801,Magearna,95,115,80,8.15,138.15,123.15,73.15,126.325,1

In [96]:
#No esta de mas comparar dos dataframes donde sabemos quienes son los pokemones legendarios ahora debemos entender porque los pokemones que se igualan a su nivel no lo son
Legendarios= Pokemon['is_legendary'] == 1
Legendarios=Pokemon[Legendarios]